#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

[ -z "$PREINIT" ] && exec /sbin/init

export PATH=/usr/sbin:/usr/bin:/sbin:/bin
export OPENSSL_CONF=/etc/ssl/openssl.cnf

pi_ifname=
pi_ip=192.168.1.1
pi_broadcast=192.168.1.255
pi_netmask=255.255.255.0

fs_failsafe_ifname=
fs_failsafe_ip=192.168.1.1
fs_failsafe_broadcast=192.168.1.255
fs_failsafe_netmask=255.255.255.0

fs_failsafe_wait_timeout=0

pi_suppress_stderr="y"
pi_init_suppress_stderr="y"
pi_init_path="/usr/sbin:/usr/bin:/sbin:/bin"
pi_init_cmd="/sbin/init"

. /lib/functions.sh
. /lib/functions/preinit.sh
. /lib/functions/system.sh

boot_hook_init preinit_essential
boot_hook_init preinit_main
boot_hook_init failsafe
boot_hook_init initramfs
boot_hook_init preinit_mount_root

#echo "Time to init apparmor
mount -t securityfs none /sys/kernel/security

#To enable most verbose output:
#printf "all" > /sys/module/apparmor/parameters/audit

# enable system wide policy
/sbin/apparmor_parser -a /etc/apparmor.d/sbin.init
/sbin/apparmor_parser -a /etc/apparmor.d/sbin.procd
/sbin/apparmor_parser -a /etc/apparmor.d/bin.busybox
/sbin/apparmor_parser -a /etc/apparmor.d/sbin.ubusd

ecc508 rover-feed-entropy-pool

for pi_source_file in /lib/preinit/*; do
	. $pi_source_file
done

boot_run_hook preinit_essential

pi_mount_skip_next=false
pi_jffs2_mount_success=false
pi_failsafe_net_message=false

boot_run_hook preinit_main
