#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

uci_apply_defaults() {
	. /lib/functions/system.sh

	cd /etc/uci-defaults || return 0
	files="$(ls)"
	[ -z "$files" ] && return 0
	mkdir -p /tmp/.uci
	for file in $files; do
		( . "./$(basename $file)" ) && rm -f "$file"
	done
	uci commit
}

boot() {
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	mkdir -p /tmp/.jail
	touch /var/log/wtmp
	touch /var/log/lastlog
	touch /tmp/resolv.conf.auto
	ln -sf /tmp/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && /bin/mount -o noatime -t debugfs debugfs /sys/kernel/debug
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	/sbin/kmodloader

	# Move uci_apply_default before /sbin/wifi in order to enable fw_printenv command
	/bin/board_detect
	uci_apply_defaults
	
	
	# temporary hack until configd exists
	/sbin/reload_config

	# create /dev/root if it doesn't exist
	[ -e /dev/root -o -h /dev/root ] || {
		rootdev=$(awk 'BEGIN { RS=" "; FS="="; } $1 == "root" { print $2 }' < /proc/cmdline)
		[ -n "$rootdev" ] && ln -s "$rootdev" /dev/root
	}

	authenticate=/sys/devices/system/qfprom/qfprom0/authenticate
	secure_boot=$(cat $authenticate)
	if [ $secure_boot -eq 1 ]; then
		[ -f /etc/config/fstab ] && rm /etc/config/fstab
	fi
	# Save Kernel crash with rover logs
	if [ -e /opt/symantec/rover/crash ]; then
        	file_list=$(ls /opt/symantec/rover/crash -1vr | grep kcrash_)
        	last_dump=$(echo $file_list | awk '{print $1}')
        	dump_num=${last_dump//[^0-9]/}
        	[ -z "$dump_num" ] && dump_num=0 || dump_num=$((dump_num+1))
        	[ -f /usr/sbin/get_kcrash_logs ] && /usr/sbin/get_kcrash_logs /opt/symantec/rover/crash $dump_num
        	# Delete old files
        	file_list=$(ls /opt/symantec/rover/crash -1v | grep kcrash_)
        	num_files=$(echo $file_list | wc -w)
        	if [ "$num_files" -gt 5 ]; then
            		rm /opt/symantec/rover/crash/$(echo $file_list | awk '{print $1}')
        	fi
	else
        	[ -f /usr/sbin/get_kcrash_logs ] && /usr/sbin/get_kcrash_logs /tmp "0"
	fi
}
